apiVersion: v1
kind: Service
metadata:
  name: kipp
  namespace: default
  labels:
    app: kipp
spec:
  selector:
    app: kipp
  ports:
    - protocol: TCP
      port: 2010
      targetPort: 443
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kipp
  labels:
    app: kipp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kipp
  template:
    metadata:
      labels:
        app: kipp
    spec:
      containers:
        - name: kipp
          image: uhthomas/kipp
          ports:
            - containerPort: 443